---

# A single playbook to execute all the tasks

- name: Begin Execution of Playbook For Interface Configurations
  import_playbook: tasks/interfaces.yml

- name: Begin Execution of Playbook For EIGRP Configuration on R1 and R2
  import_playbook: tasks/conf_eigrp.yml

  - name: Begin Execution of Playbook For OSPF Interface Configuration on R2 and R3
  import_playbook: tasks/conf_ospf_interfaces.yml

  - name: Begin Execution of Playbook For Enabling OSPF on R2 and R3
  import_playbook: tasks/enable_ospfv2.yml
  
- name: Begin Execution of Playbook For BGP Configuration on R3 and R4
  import_playbook: tasks/conf_bgp.yml




